from typing import Annotated, List, Optional, Tuple
from fastapi import APIRouter, Depends, Query
from sqlalchemy.orm import selectinload
from sqlmodel import Session, or_, select

from practice.lib.db import get_session
from practice.lib import (
    api_response,
    GetSession,
    requirePermission,
    requireSignin,
    listop,
)

from practice.mvc.models.productModel import (
    Product,
    ProductCreate,
    ProductRead,
)

router = APIRouter(prefix="/product", tags=["product"])


@router.post("/create", response_model=Product)
def create_product(
    request: ProductCreate,
    session: GetSession,
    auth=requireSignin,
    # auth=requirePermission("product_create"),
):
    # Create Product from incoming request data
    product = Product(**request.model_dump())  # like new Product(req.body)
    product.user_id = auth["id"]

    # Save to DB
    session.add(product)
    session.commit()

    # Refresh to load autogenerated fields (e.g., id)
    session.refresh(product)

    # Return structured response
    return api_response(200, "Product created", product)


@router.get(
    "/list",
    response_model=list[ProductRead],
)
def list_product(
    session: GetSession,
    dateRange: Optional[
        str
    ] = None,  # JSON string like '["created_at", "01-01-2025", "01-12-2025"]'
    numberRange: Optional[str] = None,  # JSON string like '["amount", "0", "100000"]'
    searchTerm: str = None,
    columnFilters: Optional[str] = Query(
        None
    ),  # e.g. '[["name","car"],["description","product"]]'
    page: int = None,
    skip: int = 0,
    limit: int = Query(10, ge=1, le=100),
):
    filters = {
        "searchTerm": searchTerm,
        "columnFilters": columnFilters,
        "dateRange": dateRange,
        "numberRange": numberRange,
    }
    searchFields = [
        "name",
        "description",
    ]
    result = listop(
        session=session,
        Model=Product,
        join_options=[selectinload(Product.owner)],
        searchFields=searchFields,
        filters=filters,
        skip=skip,
        page=page,
        limit=limit,
    )

    if not result["data"]:
        return api_response(404, "No products found")

    # Convert each SQLModel Product instance into a ProductRead Pydantic model
    # This ensures relationships like `owner` are included in the serialized output
    product_list = [ProductRead.model_validate(prod) for prod in result["data"]]

    return api_response(
        200,
        "Products found",
        product_list,
        result["total"],
    )


@router.get("/{id}", response_model=ProductRead)
def read(
    id: int,
    session: Session = Depends(get_session),
):
    statement = (
        select(Product).where(Product.id == id).options(selectinload(Product.owner))
    )
    result = session.exec(statement).first()
    if not result:
        return api_response(404, "Product not found")
    product = ProductRead.model_validate(result)
    return api_response(200, "Product Found", product)


@router.delete("/{id}", response_model=dict)
def delete(
    id: int,
    session: Session = Depends(get_session),
):
    user = session.get(Product, id)
    if not user:
        return api_response(404, "User not found")

    session.delete(user)
    session.commit()
    return api_response(200, f"Product {id} deleted")
