[project]
name = "practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.13",
    "sqlmodel>=0.0.24",
    "uvicorn[standard]>=0.34.3",
]
[tool.uv.scripts]
dev = "uvicorn practice.main:app --reload"
