from typing import Annotated, List
from fastapi import APIRouter, Depends, Query
from sqlalchemy.orm import selectinload
from sqlmodel import Session, or_, select

from practice.lib.db import get_session
from practice.lib import api_response, GetSession, requirePermission, requireSignin

from practice.mvc.models.productModel import (
    Product,
    ProductCreate,
    ProductRead,
)

router = APIRouter(prefix="/product", tags=["product"])


@router.post("/create", response_model=Product)
def create_product(
    request: ProductCreate,
    session: GetSession,
    auth=requirePermission("product_create"),
):
    # Create Product from incoming request data
    product = Product(**request.model_dump())  # like new Product(req.body)
    product.user_id = auth["id"]

    print(product)
    # Save to DB
    session.add(product)
    session.commit()

    # Refresh to load autogenerated fields (e.g., id)
    session.refresh(product)

    # Return structured response
    return api_response(200, "Product created", product)


def filterSearchTerms(
    Model,
    searchTerm: str | None,
    searchTerms: list[str],
    statement,
):
    if not searchTerm:
        return statement  # Don't change it if no search term

    searchFilters = [
        getattr(Model, field).ilike(f"%{searchTerm}%") for field in searchTerms
    ]

    return statement.where(or_(*searchFilters))


def paginate(
    statement,
    page: int = 1,
    limit: int = Query(10, ge=1, le=100),
):
    offset = (page - 1) * limit
    return statement.offset(offset).limit(limit)


@router.get(
    "/list",
    response_model=list[ProductRead],
)
def list_product(
    session: GetSession,
    # auth=requireSignin,
    searchTerm: str = None,
    page: int = Query(1, ge=1),
    limit: int = Query(10, ge=1, le=100),
):
    searchTerms = [
        "name",
        "description",
    ]
    # selectinload like populate in mongoose
    statement = select(Product).options(selectinload(Product.owner))  # JOIN user
    statement = filterSearchTerms(Product, searchTerm, searchTerms, statement)
    statement = paginate(statement, page, limit)
    data = session.exec(statement).all()

    if not data:
        return api_response(404, "Product not found")
    # Convert each SQLModel Product instance into a ProductRead Pydantic model
    # This ensures relationships like `owner` are included in the serialized output
    product_list = [ProductRead.model_validate(prod) for prod in data]

    return api_response(
        200,
        "Products fetched",
        product_list,
        len(product_list),
    )


@router.get("/{id}", response_model=ProductRead)
def read(
    id: int,
    session: Session = Depends(get_session),
):
    statement = (
        select(Product).where(Product.id == id).options(selectinload(Product.owner))
    )
    result = session.exec(statement).first()
    if not result:
        return api_response(404, "Product not found")
    product = ProductRead.model_validate(result)
    return api_response(200, "Product Found", product)


@router.delete("/{id}", response_model=dict)
def delete(
    id: int,
    session: Session = Depends(get_session),
):
    user = session.get(Product, id)
    if not user:
        return api_response(404, "User not found")

    session.delete(user)
    session.commit()
    return api_response(200, f"Product {id} deleted")
